In [12]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
from matplotlib import pyplot as plt 
import random

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , classification_report
from sklearn.tree import DecisionTreeClassifier

In [4]:
from sklearn.datasets import make_classification

X , y = make_classification(n_features = 5 , n_redundant = 0 , n_informative = 5 , n_clusters_per_class = 1)

In [5]:
df = pd.DataFrame(X , columns = ['col1' , 'col2' , 'col3' , 'col4' , 'col5'])
df['target'] = y 
df.shape

(100, 6)

In [6]:
df.head()

       col1      col2      col3      col4      col5  target
0 -1.780245  0.604081 -2.659685  0.929559 -1.733577       1
1 -2.069396  2.426182  0.977245  2.055542 -0.926606       0
2 -0.192365  0.836738 -1.714764  1.784444 -1.930933       1
3  1.151923  1.591165  0.940900  1.498623 -0.854705       0
4 -1.261808  3.321281 -2.586636  0.187082 -1.956993       1

In [14]:
# function for row sampling 
def sample_rows(df , percent , replace = True): 
    return df.sample(int(percent * df.shape[0]) , replace = replace)

In [24]:
# function for feature sampling 
def sample_cols(df , percent , replace = True): 
    col_list = df.columns.tolist()[ : -1]
    sample_col_count = int(percent * (df.shape[1] - 1))
    cols = random.sample(col_list , sample_col_count)
    return df[cols]

In [20]:
# function for both row and feature sampling 
def combined_sampling(df , row_percent , col_percent , replace = True): 
    new_df = sample_cols(df , col_percent , replace)
    return sample_rows(new_df , row_percent , replace)

In [26]:
# In bagging we train same type of model with different subset of data 

# make 3 datasets for 3 models
df1 = sample_rows(df , 0.1)
df2 = sample_rows(df , 0.1) 
df3 = sample_rows(df , 0.1)

In [28]:
df1.shape

(10, 6)

In [29]:
df2.shape

(10, 6)

In [30]:
df1

        col1      col2      col3      col4      col5  target
17 -1.319143  0.590934 -1.125747 -0.076143 -1.146369       1
17 -1.319143  0.590934 -1.125747 -0.076143 -1.146369       1
38  0.593039  1.489563  1.874984  1.815979  0.026765       0
59  3.098664 -0.207608  2.674586  0.813739  1.012787       0
51 -2.100370  2.420221 -4.025243  2.405554 -3.372700       1
37  2.908565  0.480512  1.533855  1.141189 -0.145143       0
79  0.285129 -1.279661 -0.391372  1.757827 -0.684026       1
5   0.116887  1.419344  0.261326  0.985460 -0.097501       1
12  2.863484  0.727892  1.291513  1.052422 -1.343960       0
50  0.249537  2.637956 -0.945450  0.245657 -3.892799       0

In [27]:
dt1 = DecisionTreeClassifier() 
dt2 = DecisionTreeClassifier() 
dt3 = DecisionTreeClassifier()

In [37]:
dt1.fit(df1.iloc[ : , : 5] , df1['target'])
dt2.fit(df2.iloc[ : , : 5] , df2['target']) 
dt3.fit(df3.iloc[ : , : 5] , df3['target'])

DecisionTreeClassifier()

In [40]:
# pick a random row to predict 
predict_row = df.iloc[76 , : ].to_numpy()

In [42]:
X_test = predict_row[ : len(predict_row) - 1]

In [44]:
X_test

array([-0.52373516, -1.37522008, -3.00969844,  0.83665999,  0.34138613])

In [47]:
print("model-1 -> prediction:" , dt1.predict(X_test.reshape(1 , 5))) 
print("model-2 -> prediction:" , dt2.predict(X_test.reshape(1 , 5))) 
print("model-3 -> prediction:" , dt3.predict(X_test.reshape(1 , 5)))

model-1 -> prediction: [1]
model-2 -> prediction: [1]
model-3 -> prediction: [1]