In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df = df[df['species'] != 0][['sepal_length' , 'sepal_width' , 'species']]

In [5]:
df.head()

   sepal_length  sepal_width species
0           5.1          3.5  setosa
1           4.9          3.0  setosa
2           4.7          3.2  setosa
3           4.6          3.1  setosa
4           5.0          3.6  setosa

In [6]:
df.shape

(150, 3)

In [7]:
X = df.drop(columns = ['species'])
y = df['species']

In [8]:
X.shape

(150, 2)

In [9]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [10]:
lr = LogisticRegression()
rf = RandomForestClassifier()
knn = KNeighborsClassifier()

In [11]:
estimators = [
    ("LogisticRegression" , lr), 
    ("RandomForestClassifier" , rf), 
    ("KNeighborsClassifier" , knn) 
]

In [12]:
# Find the accuracy of individual models
for estimator in estimators: 
    cross_val = np.mean(cross_val_score(estimator[1] , X , y , cv = 10 , scoring = 'accuracy'))
    print(f"Accuracy of {estimator[0]} is: {cross_val}")

Accuracy of LogisticRegression is: 0.8066666666666669
Accuracy of RandomForestClassifier is: 0.72
Accuracy of KNeighborsClassifier is: 0.76

### Hard Voting

In [13]:
vc = VotingClassifier(estimators = estimators)
cross_val = cross_val_score(vc , X , y , cv = 10 , scoring = 'accuracy')
print(np.mean(cross_val))

0.7733333333333333

### Soft voting

In [14]:
vc = VotingClassifier(estimators = estimators , voting = 'soft')
cross_val = cross_val_score(vc , X , y , cv = 10 , scoring = 'accuracy')
print(np.mean(cross_val))

0.7733333333333333

### Weigthed Voting

In [16]:
for i in range(1 , 4): 
    for j in range(1 , 4): 
        for k in range(1 , 4): 
            weights = [i , j , k] # weights for our 3 models

            # with hard voting 
            vc1 = VotingClassifier(estimators = estimators , voting = 'hard' , weights = weights)
            cross_val1 = cross_val_score(vc1 , X , y , cv = 10 , scoring = 'accuracy')
            cv1 = np.mean(cross_val1) 
            # print(' - ' * 30)
            print("Hard Voting")
            print(f"Weights: {weights} mean cross val: {cv1}")
            print(' - ' * 30)

            # with soft voting 
            vc2 = VotingClassifier(estimators = estimators , voting = 'soft' , weights = weights)
            cross_val2 = cross_val_score(vc2 , X , y , cv = 10 , scoring = 'accuracy')
            cv2 = np.mean(cross_val2) 
            # print(' - ' * 30)
            print("Soft Voting")
            print(f"Weights: {weights} mean cross val: {cv2}")
            print('-' * 30)

Hard Voting
Weights: [1, 1, 1] mean cross val: 0.7733333333333333
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [1, 1, 1] mean cross val: 0.76
------------------------------
Hard Voting
Weights: [1, 1, 2] mean cross val: 0.76
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [1, 1, 2] mean cross val: 0.7666666666666667
------------------------------
Hard Voting
Weights: [1, 1, 3] mean cross val: 0.76
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [1, 1, 3] mean cross val: 0.7533333333333333
------------------------------
Hard Voting
Weights: [1, 2, 1] mean cross val: 0.7533333333333333
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [1, 2, 1] mean cross val: 0.7533333333333333
------------------------------
Hard Voting
Weights: [1, 2, 2] mean cross val: 0.7666666666666666
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [1, 2, 2] mean cross val: 0.76
------------------------------
Hard Voting
Weights: [1, 2, 3] mean cross val: 0.76
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [1, 2, 3] mean cross val: 0.7533333333333333
------------------------------
Hard Voting
Weights: [1, 3, 1] mean cross val: 0.7333333333333333
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [1, 3, 1] mean cross val: 0.7266666666666667
------------------------------
Hard Voting
Weights: [1, 3, 2] mean cross val: 0.76
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [1, 3, 2] mean cross val: 0.7533333333333333
------------------------------
Hard Voting
Weights: [1, 3, 3] mean cross val: 0.7666666666666666
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [1, 3, 3] mean cross val: 0.7466666666666667
------------------------------
Hard Voting
Weights: [2, 1, 1] mean cross val: 0.78
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [2, 1, 1] mean cross val: 0.78
------------------------------
Hard Voting
Weights: [2, 1, 2] mean cross val: 0.7733333333333333
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [2, 1, 2] mean cross val: 0.7733333333333333
------------------------------
Hard Voting
Weights: [2, 1, 3] mean cross val: 0.76
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [2, 1, 3] mean cross val: 0.7666666666666667
------------------------------
Hard Voting
Weights: [2, 2, 1] mean cross val: 0.7733333333333333
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [2, 2, 1] mean cross val: 0.76
------------------------------
Hard Voting
Weights: [2, 2, 2] mean cross val: 0.7666666666666667
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [2, 2, 2] mean cross val: 0.76
------------------------------
Hard Voting
Weights: [2, 2, 3] mean cross val: 0.7733333333333333
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [2, 2, 3] mean cross val: 0.7666666666666667
------------------------------
Hard Voting
Weights: [2, 3, 1] mean cross val: 0.76
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [2, 3, 1] mean cross val: 0.7533333333333333
------------------------------
Hard Voting
Weights: [2, 3, 2] mean cross val: 0.7666666666666666
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [2, 3, 2] mean cross val: 0.7666666666666666
------------------------------
Hard Voting
Weights: [2, 3, 3] mean cross val: 0.7733333333333333
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [2, 3, 3] mean cross val: 0.7733333333333333
------------------------------
Hard Voting
Weights: [3, 1, 1] mean cross val: 0.8066666666666669
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [3, 1, 1] mean cross val: 0.8
------------------------------
Hard Voting
Weights: [3, 1, 2] mean cross val: 0.78
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [3, 1, 2] mean cross val: 0.78
------------------------------
Hard Voting
Weights: [3, 1, 3] mean cross val: 0.78
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [3, 1, 3] mean cross val: 0.7866666666666666
------------------------------
Hard Voting
Weights: [3, 2, 1] mean cross val: 0.78
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [3, 2, 1] mean cross val: 0.78
------------------------------
Hard Voting
Weights: [3, 2, 2] mean cross val: 0.76
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [3, 2, 2] mean cross val: 0.7666666666666667
------------------------------
Hard Voting
Weights: [3, 2, 3] mean cross val: 0.7666666666666666
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [3, 2, 3] mean cross val: 0.7666666666666667
------------------------------
Hard Voting
Weights: [3, 3, 1] mean cross val: 0.7666666666666667
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [3, 3, 1] mean cross val: 0.74
------------------------------
Hard Voting
Weights: [3, 3, 2] mean cross val: 0.7666666666666666
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [3, 3, 2] mean cross val: 0.7666666666666666
------------------------------
Hard Voting
Weights: [3, 3, 3] mean cross val: 0.7733333333333333
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
Soft Voting
Weights: [3, 3, 3] mean cross val: 0.7533333333333333
------------------------------